aliases:
  - keyword
  - keywords
  - search query
  - search queries
  - query
  - queries
  - search term
  - search terms
  - term
  - keyword text
  - organic keyword
  - top queries
  - search keyword
