"""Base exporter framework."""

from abc import ABC, abstractmethod
from pathlib import Path

from keyword_intelligence.models.pipeline import PipelineResult
from keyword_intelligence.pipeline.context import PipelineContext


class BaseExporter(ABC):
    """Abstract base class for all pipeline output exporters."""

    @abstractmethod
    def export(
        self, result: PipelineResult, context: PipelineContext, output_dir: Path
    ) -> list[str]:
        """Export the result into the output directory.

        Args:
            result: The final PipelineResult containing metrics and summary.
            context: The PipelineContext containing the DataFrame.
            output_dir: The timestamped output directory.

        Returns:
            A list of absolute file paths generated by this exporter.
        """
        pass
