"""Scorer for combining confidence from multiple duplicate strategies."""

from __future__ import annotations

from keyword_intelligence.duplicate_detection.models import DuplicateCandidate


class DuplicateScorer:
    """Heuristic engine for scoring duplicate matches."""

    def score_candidates(
        self, candidates: list[DuplicateCandidate]
    ) -> list[DuplicateCandidate]:
        """Optionally adjust confidences based on overlapping strategy matches.

        For Phase 3A, the strategies output their own static or calculated confidence.
        If we needed to combine multiple weak signals (e.g., fuzzy + semantic),
        we would do that here.

        Args:
            candidates: The raw candidates generated by strategies.

        Returns:
            The candidates with finalized confidences.
        """
        # In the future, we could look for candidates where keyword A matches keyword B
        # in multiple strategies and boost the confidence.
        # For now, we just pass them through as strategies provide robust confidences.
        return candidates
